var vg_1 = "charts/chart1_internet_trend.vg.json";
var vg_2 = "charts/chart2_map_state_usage.vg.json";
var vg_3 = "charts/chart3_slope_lifestyle.vg.json";
var vg_4 = "charts/chart4_faceted_age_activities.vg.json";
var vg_5 = "charts/chart5_heatmap_state_activities.vg.json";
var vg_6 = "charts/chart6_state_selector.vg.json";
var vg_7 = "charts/chart7_age_trends_lines.vg.json";
var vg_8 = "charts/chart8_lifestyle_comparison.vg.json";
var vg_9 = "charts/chart9_simple.vg.json";
var vg_10 = "charts/chart10_interactive_drilldown.vg.json";

vegaEmbed("#chart1", vg_1);
vegaEmbed("#chart2", vg_2);
vegaEmbed("#chart3", vg_3);
vegaEmbed("#chart4", vg_4);
vegaEmbed("#chart5", vg_5);
vegaEmbed("#chart6", vg_6);
vegaEmbed("#chart7", vg_7);
vegaEmbed("#chart8", vg_8);
vegaEmbed("#chart9", vg_9).catch(console.error);
vegaEmbed("#chart10", vg_10);
